
GET http://localhost:8080
Content-Type: application/json
###

POST http://localhost:8080/post-a-book
Content-Type: application/json

{
    "name": "timothy",
    "gender": "male"

}

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "firstName": "ade",
    "lastName": "joy",
    "email": "ade@ade.com",
    "password": "AW123@904959595"
}